FROM kalilinux/kali-rolling:latest

WORKDIR /scripts
WORKDIR /data

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get dist-upgrade -y

RUN apt-get install -y locate wget git vim golang python3 python3-pip nmap nikto hydra sublist3r gobuster

# Defina as variáveis de ambiente do Go
ENV GOPATH=/root/go
ENV PATH=$PATH:$GOPATH/bin

# Instale ferramentas Go
RUN go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
RUN mv /root/go/bin/subfinder /usr/bin/

RUN go install github.com/tomnomnom/assetfinder@latest
RUN mv /root/go/bin/assetfinder /usr/bin/

RUN go install github.com/openrdap/rdap/cmd/rdap@latest
RUN mv /root/go/bin/rdap /usr/bin/

RUN go install github.com/projectdiscovery/httpx/cmd/httpx@latest
RUN mv /root/go/bin/httpx /usr/bin/

RUN go install github.com/tomnomnom/waybackurls@latest
RUN mv /root/go/bin/waybackurls /usr/bin/

RUN go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
RUN mv /root/go/bin/nuclei /usr/bin/
RUN nuclei -update-templates
